version: "3.7"


loki:
  image: grafana/loki
  container_name: loki
  volumes:
    - ./loki/loki-config.yaml:/mnt/config/loki-config.yaml:ro
    - ./loki/data/:/tmp/loki
  ports:
    - 3100:3100
  command:
    - '-config.file=/mnt/config/loki-config.yaml'
  restart: always
  networks:
    - t4y