version: "3.7"
####################TEMPO#########################
tempo:
  image: grafana/tempo:latest
  container_name: tempo
  ports:
    - 3200:3200
    - 14317:4317  # OTLP gRPC
    - 14318:4318  # OTLP HTTP
  volumes:
    - ./tempo/tempo-config.yaml:/etc/tempo/tempo-config.yaml:ro  # 설정 파일을 읽기 전용으로 마운트
    - ./tempo/data:/data/tempo  # 트레이스 데이터를 저장할 디렉토리 마운트
  command:
    - -config.file=/etc/tempo/tempo-config.yaml  # Tempo 실행 시 사용할 설정 파일 지정

  networks:
    - t4y
####################TEMPO#########################
