stream_over_http_enabled: true
server:
  http_listen_port: 3200  # HTTP 요청을 받을 포트
#  grpc_listen_port: 9095  # gRPC 요청 포트 추가

compactor:
  compaction:
    block_retention: 24h  # 24시간 동안 트레이스 블록 유지

metrics_generator:
  registry:
    external_labels:
      source: tempo
#      cluster: linux-microservices
  storage:
    path: /var/tempo/generator/wal
    remote_write:
    - url: http://mimir:9009/prometheus/api/v1/write
      send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces
  processor:
    local_blocks:
      filter_server_spans: false
      flush_to_storage: true


distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "tempo:14317"
        http:
          endpoint: "tempo:14318"

storage:
  trace:
    backend: local  # 로컬 파일 시스템을 저장소로 사용
    local:
      path: /var/tempo/blocks  # 트레이스 데이터를 저장할 경로 지정

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks]
      generate_native_histograms: both