server:
  http_listen_port: 3200  # HTTP 요청을 받을 포트
  grpc_listen_port: 9095  # gRPC 요청 포트 추가
#  http2_max_frame_size: 1048576  # HTTP/2 프레임 크기 증가 (1MB)
#  http2_max_concurrent_streams: 250  # 동시 스트림 개수 증가
#  http2_max_read_frame_size: 1048576  # 읽기 프레임 크기 증가
  grpc_server_max_recv_msg_size: 104857600  # 100MB로 설정 (기본보다 높임)
  grpc_server_max_send_msg_size: 104857600  # 100MB로 설정

compactor:
  compaction:
    block_retention: 24h  # 24시간 동안 트레이스 블록 유지

metrics_generator:
  registry:
    external_labels:
      source: tempo
#      cluster: linux-microservices
  storage:
    path: /data/tempo/generator/wal
    remote_write:
    - url: http://localhost:9090/api/v1/write
      send_exemplars: true


distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

storage:
  trace:
    backend: local  # 로컬 파일 시스템을 저장소로 사용
    local:
      path: /data/tempo/blocks  # 트레이스 데이터를 저장할 경로 지정

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]


#querier:
#  frontend_worker:
#    frontend_address: 127.0.0.1:4317
#  grpc_client_config:
#    max_recv_msg_size: 104857600  # 수신 메시지 크기 증가 (100MB)
#    max_send_msg_size: 104857600  # 송신 메시지 크기 증가 (100MB)

#frontend:
#  log_received_spans: true
#  log_received_traces: true
#  max_outstanding_per_tenant: 1000
#  scheduler_address: 127.0.0.1:4317