
####################GRAFANA#######################
version: "3.7"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000

    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
#    volumes:
#      - grafana-data:/var/lib/grafana
    #      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
    depends_on:
      - mimir
      - tempo
      - loki
    networks:
      - t4y
####################GRAFANA#######################
