server:
  http_listen_port: 9009  # HTTP 요청을 받을 포트 설정
  grpc_listen_port: 9095  # gRPC 요청을 받을 포트 설정

common:
  storage:
    backend: s3
    s3:
      entrypoint: minio:9000
      access_key_id: admin
      secret_access_key: abcd1234
      insecure: true
      bucket_name: mimir-data

blocks_storage:
  storage_prefix: blocks
  tsdb:
    dir: /data/ingester

compactor:
  compaction_interval: 10m  # 블록 정리를 수행하는 간격 (10분)

memberlist:
  join_members: [mimir]

ingester:
  ring:
    kvstore:
      store: memberlist
    replication_factor: 1
    heartbeat_period: 5s
    instance_id: "ingester-1"

distributor:
  ring:
    kvstore:
      store: memberlist  # 멤버 리스트 기반의 키-값 저장소 사용 (클러스터링)

ruler:
  rule_path: /data/mimir/rules  # 룰을 저장할 로컬 디렉토리 경로 지정