version: "3.7"

services:
  mimir:
    image: grafana/mimir:latest # 사용할 Mimir 컨테이너 이미지 지정
    container_name: mimir  # 컨테이너 이름 설정
    ports:
      - 9009:9009 # 호스트와 컨테이너 간의 HTTP 포트 매핑
      - 9095:9095  # 호스트와 컨테이너 간의 gRPC 포트 매핑
    volumes:
      - ./mimir/mimir-config.yaml:/etc/mimir/mimir-config.yaml:ro   # 설정 파일을 컨테이너 내에 읽기 전용으로 마운트
      - ./mimir/data:/data/mimir  # 데이터를 저장할 디렉토리를 마운트
    command: -config.file=/etc/mimir/mimir-config.yaml # Mimir 실행 시 사용할 설정 파일 지정
    restart: always  # 컨테이너가 중단될 경우 자동 재시작
    networks:
      - t4y